name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TAGPR_TOKEN }}
      - uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.TAGPR_TOKEN }}
